global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'flashsale-api'
    static_configs:
      - targets: ['api:8080']
        labels:
          application: 'flashsale-engine'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
